// This string is autogenerated by ChangeAppSettings.sh, do not change
// spaces amount
package org.renpy.android;

import java.io.*;

import android.app.Activity;
import android.util.Log;

////////////////////////////////////////////////////////////////////////////////////////////////

import java.util.zip.GZIPInputStream; // 导入 GZIP 解压缩输入流
import java.util.zip.ZipEntry; // 导入 ZIP 文件条目
import java.util.zip.ZipInputStream; // 导入 ZIP 输入流

////////////////////////////////////////////////////////////////////////////////////////////////

import android.content.res.AssetManager;

import org.kamranzafar.jtar.*;

class AssetExtract { //这里是原版解压

    private AssetManager mAssetManager = null;
    private Activity mActivity = null;
    private static final String TAG = "AssetExtract";

    AssetExtract(Activity act) {
        mActivity = act;
        mAssetManager = act.getAssets();
    }

    public boolean extractTar(String asset, String target) {

        byte buf[] = new byte[1024 * 1024];

        InputStream assetStream = null;
        TarInputStream tis = null;

        Log.i("python", "extracting " + asset + " to " + target);
        
        try {
            assetStream = mAssetManager.open(asset, AssetManager.ACCESS_STREAMING);
            tis = new TarInputStream(new BufferedInputStream(new GZIPInputStream(new BufferedInputStream(assetStream, 8192)), 8192));
        } catch (IOException e) {
            Log.e("python", "opening up extract tar", e);
            return false;
        }

        while (true) {
            TarEntry entry = null;

            try {
                entry = tis.getNextEntry();
            } catch ( java.io.IOException e ) {
                Log.e("python", "extracting tar", e);
                return false;
            }

            if ( entry == null ) {
                break;
            }

            // Log.i("python", "extracting " + entry.getName());

            if (entry.isDirectory()) {

                try {
                    new File(target +"/" + entry.getName()).mkdirs();
                } catch ( SecurityException e ) { };

                continue;
            }

            OutputStream out = null;
            String path = target + "/" + entry.getName();

            try {
                out = new BufferedOutputStream(new FileOutputStream(path), 8192);
            } catch ( FileNotFoundException e ) {
            } catch ( SecurityException e ) { };

            if ( out == null ) {
                Log.e("python", "could not open " + path);
                return false;
            }

            try {
                while (true) {
                    int len = tis.read(buf);

                    if (len == -1) {
                        break;
                    }

                    out.write(buf, 0, len);
                }

                out.flush();
                out.close();
            } catch ( java.io.IOException e ) {
                Log.e("python", "extracting zip", e);
                return false;
            }
        }

        try {
            tis.close();
            assetStream.close();
        } catch (IOException e) {
            // pass
        }

        return true;
    }

////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * 将 assets 下的文件拷贝到目标目录
     */
    // 复制用方法
    public void copyAsset(String assetName, String destPath) {
        InputStream in = null;
        FileOutputStream out = null;
        try {
            in = mAssetManager.open(assetName);
            File outFile = new File(destPath);
            File parent = outFile.getParentFile();
            if (parent != null && !parent.exists()) {
                parent.mkdirs();
            }
            out = new FileOutputStream(outFile);

            byte[] buffer = new byte[4096];
            int read;
            while ((read = in.read(buffer)) != -1) {
                out.write(buffer, 0, read);
            }
            out.flush();
            Log.i(TAG, "复制成功: " + assetName + " -> " + destPath);
        } catch (IOException e) {
            Log.e(TAG, "复制失败: " + assetName, e);
        } finally {
            try {
                if (in != null) in.close();
                if (out != null) out.close();
            } catch (IOException ignored) {}
        }
    }

    /**
     * 解压特定的 assets 压缩包到目标目录
     */
    public void unzipSpecificGameZip(String assetZipName, String destDirectoryName) {
        String zipPath = mActivity.getFilesDir().getAbsolutePath() + "/" + assetZipName + ".zip";
        String destDirectory = mActivity.getFilesDir().getAbsolutePath() + "/" + destDirectoryName;
        
        // 先把apk中的 assets/assetZipName.zip 拷贝到 files/
        copyAsset(assetZipName + ".zip", zipPath);

        try {
            unzip(zipPath, destDirectory);
            Log.i(TAG, assetZipName + ".zip 解压完成: " + destDirectory);
        } catch (IOException e) {
            Log.e(TAG, assetZipName + ".zip 解压失败: " + zipPath, e);
        }
    }

    /**
     * 解压 zip 文件到目标目录
     * 如果目标目录已经存在且不为空，则跳过解压
     * 如果目标目录不存在，则创建该目录
     */

    //  这里定义了解压 ZIP 文件的通用方法
    public void unzip(String zipFilePath, String destDirectory) throws IOException {
        File destDir = new File(destDirectory);
        if (destDir.exists() && destDir.isDirectory() && destDir.list().length > 0) {
            Log.i(TAG, "跳过解压，目录已存在: " + destDirectory);
         return;
        }

        if (!destDir.exists()) {
            destDir.mkdirs();
        }

        byte[] buffer = new byte[32768];
        try (FileInputStream fis = new FileInputStream(zipFilePath);
            ZipInputStream zis = new ZipInputStream(fis)) {

            ZipEntry entry = zis.getNextEntry();
            while (entry != null) {
                File newFile = newFile(destDir, entry);

                if (entry.isDirectory()) {
                    if (!newFile.isDirectory() && !newFile.mkdirs()) {
                        throw new IOException("创建目录失败: " + newFile);
                    }
                } else {
                    // 确保父目录存在
                    File parent = newFile.getParentFile();
                    if (!parent.isDirectory() && !parent.mkdirs()) {
                        throw new IOException("创建父目录失败: " + parent);
                    }

                    // 写文件
                    try (FileOutputStream fos = new FileOutputStream(newFile)) {
                        int len;
                        while ((len = zis.read(buffer)) > 0) {
                            fos.write(buffer, 0, len);
                        }
                    }
                    Log.i(TAG, "解压文件: " + newFile.getAbsolutePath());
                }
                zis.closeEntry();
                try {
                    entry = zis.getNextEntry();
                } catch (IllegalArgumentException e) {
                    Log.e(TAG, "ZIP 文件格式不正确或文件损坏: " + entry.getName(), e);
                    continue; // 跳过当前文件，继续解压下一个文件
                }
            }

            zis.closeEntry();
        } catch (IOException e) {
            Log.e(TAG, "解压失败: " + zipFilePath, e);
            throw e;
        }

        Log.i(TAG, "解压完成: " + zipFilePath + " -> " + destDirectory);
    }

    /**
     * 防止 Zip Slip 漏洞
     */
    
    private File newFile(File destinationDir, ZipEntry zipEntry) throws IOException {
        File destFile = new File(destinationDir, zipEntry.getName());

        String destDirPath = destinationDir.getCanonicalPath(); // 根据条目名创建 File 对象
        String destFilePath = destFile.getCanonicalPath();

        if (!destFilePath.startsWith(destDirPath + File.separator)) {
            throw new IOException("解压错误: " + zipEntry.getName()); // 调试日志
        }

        return destFile;
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////